[package]
name = "convbtc"
version = "0.1.0"
edition = "2018"
authors = ["Daniel P. Teberian"]

[dependencies]
derive_more = "0.14.0"
reqwest = "0.9.12"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
structopt = "0.2.15"
